server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: rating
          uri: http://localhost:8081
          predicates:
            - Path=/ratingInfos/**, 
        - id: screen
          uri: http://localhost:8082
          predicates:
            - Path=/screens/**, 
        - id: dashboard
          uri: http://localhost:8083
          predicates:
            - Path=, /reservationInfos/**, /movieRatingInfos/**
        - id: payment
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**, 
        - id: reservation
          uri: http://localhost:8085
          predicates:
            - Path=/reservations/**, 
        - id: movie
          uri: http://localhost:8086
          predicates:
            - Path=/movies/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rating
          uri: http://rating:8080
          predicates:
            - Path=/ratingInfos/**, 
        - id: screen
          uri: http://screen:8080
          predicates:
            - Path=/screens/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, /reservationInfos/**, /movieRatingInfos/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**, 
        - id: movie
          uri: http://movie:8080
          predicates:
            - Path=/movies/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
